const express = require("express");
const router = express.Router();

const splitApi = require("./apis/splitApi");  
const compressApi = require("./apis/compressApi");  
const rotateApi = require("./apis/rotateApi");  
const imageToPdfApi = require("./apis/imageToPdfApi");  
const wordToPdfApi = require("./apis/wordToPdfApi");
const pptToPdfApi = require("./apis/pptToPdfApi");
const excelToPdfApi = require("./apis/excelToPdfApi");  
const htmlToPdfApi = require("./apis/htmlToPdfApi");        
const textToPdfApi = require("./apis/textToPdfApi");    
const pdfToImageApi = require("./apis/pdfToImagesApi");
const watermarkApi = require("./apis/watermarkApi");
const removePagesApi = require("./apis/removePagesApi"); 
const extractPagesApi = require("./apis/extractPagesApi");         
const pageNumbersApi = require("./apis/pageNumberApi");  
const pdfOrganizerApi = require("./apis/pdfOrganizerApi");     
const pdfToWordApi = require("./apis/pdfToWordApi");      
const pdfToTextApi = require("./apis/pdfToTextApi");
const pdfToExcelApi = require("./apis/pdfToExcelApi");  
const pdfToPptApi = require("./apis/pdfToPptApi");   
const pdflockApi = require("./apis/pdfLockApi"); 
const pdfUnlockApi = require("./apis/pdfUnlockApi");   
const pdfSignApi = require("./apis/pdfSignApi");
const ocrPdfApi = require("./apis/ocrPdfApi");
const clickApi = require("./apis/click");

router.use("/split", splitApi);  
router.use("/compress", compressApi);  
router.use("/rotate", rotateApi);  
router.use("/imagetopdf", imageToPdfApi);
router.use("/wordtopdf", wordToPdfApi);
router.use("/ppttopdf", pptToPdfApi);
router.use("/exceltopdf", excelToPdfApi);   
router.use("/html-to-pdf", htmlToPdfApi); 
router.use("/texttopdf", textToPdfApi);     
router.use("/pdftoimage", pdfToImageApi);
router.use("/watermark", watermarkApi);
router.use("/removepages", removePagesApi); 
router.use("/extractpages", extractPagesApi);   
router.use("/pagenumbers", pageNumbersApi);
router.use("/pdforganizer", pdfOrganizerApi);   
router.use("/pdftoword", pdfToWordApi);
router.use("/pdftotext", pdfToTextApi);
router.use("/pdftoexcel", pdfToExcelApi);   
router.use("/pdftoppt", pdfToPptApi);
router.use("/pdflock", pdflockApi);
router.use("/pdfunlock", pdfUnlockApi);
router.use("/pdfsign", pdfSignApi);
router.use("/ocr", ocrPdfApi); 
router.use("/click", clickApi);

module.exports = router;